name: build-and-tests
on:
  push:
    tags:
      - v*
    branches:
      - master
jobs:
  build:
    name: build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Tests
        run: go test ./...

      - name: Tests race condition
        run: go test -race ./...